#include <stdio.h>
//#include "configuacion.h"


//Todas las opciones para guardar la partida, crear, cargar...



/* ME HA ABIERTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*/
/* ME HA ABIERTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO X222222222222222*/


